CREATE TABLE CUSTOMER (
                          PERSONAL_ACCOUNT_ID NUMERIC GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT CUSTOMER_PK PRIMARY KEY,
                          MSISDN NUMERIC(15) NOT NULL CONSTRAINT CUSTOMER_UNIQUE_MSISDN UNIQUE,
                          ACTIVE NUMERIC(1) NOT NULL CHECK (ACTIVE IN (0, 1))
);
CREATE TABLE BALANCE (
                         BALANCE_ID NUMERIC GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT BALANCE_PK PRIMARY KEY,
                         PERSONAL_ACCOUNT_ID NUMERIC(20) NOT NULL,
                         BALANCE NUMERIC(9),
                         BALANCE_CHANGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT BALANCE_CUSTOMER_FK FOREIGN KEY (PERSONAL_ACCOUNT_ID) REFERENCES CUSTOMER (PERSONAL_ACCOUNT_ID)
);

CREATE OR REPLACE TRIGGER AFTER_CUSTOMER_INSERT
    AFTER INSERT ON CUSTOMER
    FOR EACH ROW
BEGIN
INSERT INTO BALANCE (PERSONAL_ACCOUNT_ID, BALANCE) VALUES (:new.PERSONAL_ACCOUNT_ID, 0);
END;
