CREATE TABLE PAYMENT (
                         PAYMENT_ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
                         PAYMENT_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
                         EXTERNAL_OPERATION_ID NUMERIC(20) NOT NULL,
                         PERSONAL_ACCOUNT_ID NUMERIC(20) NOT NULL,
                         TRANSACTION_AMOUNT NUMERIC(9),
                         SUCCESS NUMERIC(1) NOT NULL CHECK (SUCCESS IN (0, 1)),
                         PAYMENT_MOMENT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT PAYMENT_CUSTOMER_FK FOREIGN KEY (PERSONAL_ACCOUNT_ID) REFERENCES CUSTOMER (PERSONAL_ACCOUNT_ID)
);

CREATE INDEX PAYMENT_OPERATION_ID ON PAYMENT(EXTERNAL_OPERATION_ID);