CREATE OR REPLACE TRIGGER AFTER_PAYMENT_INSERT
    AFTER INSERT ON PAYMENT
    FOR EACH ROW
DECLARE
    oldBalance NUMERIC(9);
BEGIN
    IF :new.SUCCESS = 1 THEN
            oldBalance := 0;
        SELECT BALANCE INTO oldBalance FROM BALANCE WHERE PERSONAL_ACCOUNT_ID = :new.PERSONAL_ACCOUNT_ID;
        UPDATE BALANCE set
            BALANCE = oldBalance + :new.TRANSACTION_AMOUNT,
            BALANCE_CHANGE_DATE = CURRENT_TIMESTAMP
        WHERE PERSONAL_ACCOUNT_ID = :new.PERSONAL_ACCOUNT_ID;
    END IF;
END;
/