-- Изменить сессию
alter session set "_ORACLE_SCRIPT"=true;

-- Создать пользователя
CREATE USER CS_TEST IDENTIFIED BY "1qaz2wsx";

-- Привилегии
grant create session to CS_TEST;
grant create table to CS_TEST;
grant create procedure TO CS_TEST;
GRANT create trigger TO CS_TEST;
GRANT create VIEW TO CS_TEST;
GRANT create SEQUENCE TO CS_TEST;
GRANT ALTER ANY TABLE TO CS_TEST;
GRANT ALTER ANY PROCEDURE TO CS_TEST;
GRANT ALTER ANY TRIGGER TO CS_TEST;
GRANT ALTER PROFILE TO CS_TEST;
GRANT DELETE ANY TABLE TO CS_TEST;
GRANT DROP ANY TABLE TO CS_TEST;
GRANT DROP ANY PROCEDURE TO CS_TEST;
GRANT DROP ANY TRIGGER TO CS_TEST;
GRANT DROP ANY VIEW TO CS_TEST;
GRANT DROP PROFILE TO CS_TEST;

-- Дать привилегии на чтение системных view
GRANT SELECT ON SYS.V_$SESSION TO CS_TEST;
GRANT SELECT ON SYS.V_$SESSTAT TO CS_TEST;
GRANT SELECT ON SYS.V_$STATNAME TO CS_TEST;
GRANT SELECT ANY DICTIONARY TO CS_TEST;

ALTER USER CS_TEST quota 100M on USERS;
